title:             Clean Blog
email:             sb5449@nyu.edu
description:       A Blog Theme by Start Bootstrap
author:            Start Bootstrap
baseurl:           "http://SonghaBan.github.io/SonghaBan.github.io"
url:               "http://SonghaBan.github.io/SonghaBan.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
